title: Frnas Bukhari
logo: assets/img/headshot.jpeg
description: Frnas Bukhari, AI & Computer Science student at the University of Birmingham. Experienced in AI-driven solutions through roles at PwC and P&G, with a passion for Business intelligence and innovation.
show_downloads: false
theme: jekyll-theme-minimal
